/**
 * IN-CLASS ASSESSMENT: Movie API
 * Total: 10 marks
 * Time: 170 minutes
 * 
 * INSTRUCTIONS:
 * Create a simple Movie API using Express, TypeScript, and MongoDB.
 * Complete all 10 tasks marked with TODO comments below.
 * Each task is worth 1 mark.
 * 
 * SETUP & RUN:
 * 1. Install dependencies:
 *    npm install
 * 
 * 2. Create a .env file (copy from .env.example):
 *    DB_CONN_STRING=mongodb+srv://username:password@cluster.mongodb.net/
 *    DB_NAME=movieDB
 *    COLLECTION_NAME=movies
 * 
 * 3. Run the development server:
 *    npm run dev
 *    (Server will start at http://localhost:5000)
 * 
 * 4. Test your endpoints using Postman, Thunder Client, or curl
 * 
 * BEFORE YOU START:
 * - Read through ALL TODO tasks first
 * - Look at the MOVIE SCHEMA below
 * - Reference your previous sushi API code if needed
 * 
 * MOVIE SCHEMA:
 * {
 *   _id: ObjectId (auto-generated by MongoDB)
 *   title: string (required)
 *   director: string (required)
 *   year: number (required, must be between 1900 and current year)
 *   rating: number (required, must be between 1 and 10)
 * }
 */

// ============================================================================
// TODO #1: Import Required Dependencies (1 mark)
// Import: express (including Request, Response types), mongodb (including 
// MongoClient, Db, Collection, ObjectId), and dotenv
// ============================================================================

// YOUR CODE HERE
import express, { Request, Response } from "express";
import { MongoClient, Db, Collection, ObjectId } from "mongodb";
import dotenv from "dotenv";

// ============================================================================
// TODO #2: Create Movie Interface (1 mark)
// Create a TypeScript interface called 'Movie' with the following properties:
// - _id (optional, ObjectId type)
// - title (string)
// - director (string)
// - year (number)
// - rating (number)
// ============================================================================

// YOUR CODE HERE
interface Movie {
  _id?: ObjectId;
  title: string;
  director: string;
  year: number;
  rating: number;
}


// ============================================================================
// TODO #3: Initialize Express App and Environment Variables (1 mark)
// - Configure dotenv to load environment variables
// - Create an Express app instance
// - Set port to 5000
// - Add express.json() middleware to parse JSON bodies
// ============================================================================

// YOUR CODE HERE
dotenv.config();

const app = express();
const port = 5000;

app.use(express.json());

// Global collection variable
let moviesCollection!: Collection<Movie>;


// ============================================================================
// TODO #4: Create Database Connection Function (1 mark)
// Create an async function called 'connectToDatabase' that:
// - Gets DB_CONN_STRING, DB_NAME, and COLLECTION_NAME from environment variables
// - Throws an error if any are missing
// - Connects to MongoDB using MongoClient
// - Returns the movies collection
// - Console.logs a success message with database and collection names
// ============================================================================

// YOUR CODE HERE
async function connectToDatabase(): Promise<Collection<Movie>> {
  const connString = process.env.DB_CONN_STRING;
  const dbName = process.env.DB_NAME;
  const collectionName = process.env.COLLECTION_NAME;

  if (!connString || !dbName || !collectionName) {
    throw new Error("Missing environment variables");
  }

  const client = new MongoClient(connString);
  await client.connect();

  const db: Db = client.db(dbName);
  const collection: Collection<Movie> = db.collection(collectionName);

  console.log(`Connected to DB: ${dbName}, Collection: ${collectionName}`);

  return collection;
}


// ============================================================================
// TODO #5: GET /api/movies - Get All Movies (1 mark)
// Create a GET endpoint that:
// - Fetches all movies from the database using .find({}).toArray()
// - Returns status 200 with the array of movies
// - Handles errors with try-catch and returns status 500 with error message
// ============================================================================

// YOUR CODE HERE
app.get("/api/movies", async (req: Request, res: Response) => {
  try {
    const movies = await moviesCollection.find({}).toArray();
    res.status(200).json(movies);
  } catch (error) {
    res.status(500).json({ message: "Error fetching movies", error });
  }
});

// ============================================================================
// TODO #6: GET /api/movies/:id - Get Movie by ID (1 mark)
// Create a GET endpoint that:
// - Gets the id from route parameters
// - Creates a query using ObjectId with the id
// - Uses .findOne() to get a single movie
// - Returns 404 if movie not found, 200 with movie if found
// - Handles errors with try-catch and returns status 500
// ============================================================================

// YOUR CODE HERE
app.get("/api/movies/:id", async (req: Request, res: Response) => {
  try {
    const id: string = req.params.id;

    // Validate ObjectId
    if (!ObjectId.isValid(id)) {
      return res.status(400).json({ message: "Invalid ID format" });
    }

    const movie = await moviesCollection.findOne({
      _id: new ObjectId(id),
    });

    // If not found
    if (!movie) {
      return res.status(404).json({ message: "Movie not found" });
    }

    // If found
    res.status(200).json(movie);
  } catch (error) {
    res.status(500).json({ message: "Error fetching movie", error });
  }
});
// ============================================================================
// TODO #7: POST /api/movies - Create New Movie (1 mark)
// Create a POST endpoint that:
// - Gets movie data from request body
// - Uses .insertOne() to add the movie to database
// - Returns status 201 with success message and insertedId if successful
// - Returns status 500 if insertion fails
// - Handles errors appropriately
// ============================================================================

// YOUR CODE HERE
app.post("/api/movies", async (req: Request, res: Response) => {
  try {
    const movie: Movie = req.body;

    const result = await moviesCollection.insertOne(movie);

    res.status(201).json({
      message: "Movie created",
      id: result.insertedId,
    });
  } catch (error) {
    res.status(500).json({ message: "Error creating movie", error });
  }
});

// ============================================================================
// TODO #8: PUT /api/movies/:id - Update Movie (1 mark)
// Create a PUT endpoint that:
// - Gets id from route parameters and update data from request body
// - Creates a query using ObjectId
// - Uses .updateOne() with $set operator
// - Returns 404 if no movie was modified, 200 with success message if updated
// - Handles errors with try-catch
// ============================================================================

// YOUR CODE HERE
app.put("/api/movies/:id", async (req: Request, res: Response) => {
  try {
    const id = req.params.id as string; // ✅ fix

    const updateData = req.body;

    const result = await moviesCollection.updateOne(
      { _id: new ObjectId(id) },
      { $set: updateData }
    );

    if (result.modifiedCount === 0) {
      return res.status(404).json({ message: "Movie not found" });
    }

    return res.status(200).json({ message: "Movie updated" });
  } catch (error) {
    return res.status(500).json({ message: "Error updating movie" });
  }
});

// ============================================================================
// TODO #9: DELETE /api/movies/:id - Delete Movie (1 mark)
// Create a DELETE endpoint that:
// - Gets id from route parameters
// - Creates a query using ObjectId
// - Uses .deleteOne() to remove the movie
// - Returns 404 if no movie was deleted, 200 with success message if deleted
// - Handles errors with try-catch
// ============================================================================

// YOUR CODE HERE

app.delete("/api/movies/:id", async (req: Request, res: Response) => {
  try {
    const id = req.params.id as string; // ✅ fix

    const result = await moviesCollection.deleteOne({
      _id: new ObjectId(id),
    });

    if (result.deletedCount === 0) {
      return res.status(404).json({ message: "Movie not found" });
    }

    return res.status(200).json({ message: "Movie deleted" });
  } catch (error) {
    return res.status(500).json({ message: "Error deleting movie" });
  }
});

// ============================================================================
// TODO #10: Start Server with Database Connection (1 mark)
// - Call connectToDatabase() with .then()
// - Store the returned collection in a variable (let moviesCollection)
// - Start the Express server on the specified port inside .then()
// - Console.log server URL when started
// - Catch any database errors, log them, and exit process
// ============================================================================

// YOUR CODE HERE
connectToDatabase()
  .then((collection) => {
    moviesCollection = collection;

    app.listen(port, () => {
      console.log(`Server running at http://localhost:${port}`);
    });
  })
  .catch((error) => {
    console.error("Database connection failed:", error);
    process.exit(1);
  });

// ============================================================================
// TESTING CHECKLIST (for students):
// ============================================================================
// [ ] GET /api/movies - Returns empty array initially
// [ ] POST /api/movies - Creates a new movie with valid data
// [ ] GET /api/movies - Returns array with the created movie
// [ ] GET /api/movies/:id - Returns single movie with valid ID
// [ ] GET /api/movies/:id - Returns 404 with invalid ID
// [ ] PUT /api/movies/:id - Updates movie with valid ID and data
// [ ] DELETE /api/movies/:id - Deletes movie with valid ID
// [ ] All endpoints handle errors properly
// [ ] Server connects to database successfully
// [ ] Code uses proper TypeScript types
